Fixup crash when filefilter contains comments
The _ProcessFilterLine function returned None when a comment was found
instead of the filter.
The caller replaces the filter with the function return value.
The next call then crashed with the following error:
    'NoneType' object has no attribute 'AddCppChecker'

The filter is now returned in this case as well